In [8]:
import numpy as np

xy = np.loadtxt('data-01-test-score.csv',delimiter=',', dtype=np.float32)
x_data = xy[:,0:-1] # 2차원 리스트의 인덱싱 // 전체 열의, 0:-1을 가져와라
y_data = xy[:,[-1]]

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(6, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]


In [9]:
# 큐 러너 ( Queue runner)
# 많은 파일을 로드해서 쓸 때 유용

'''
#1
filename_queue = tf.train.string_input_producer(['file1','file2',...],shuffle=False, name='filename_queue')

#2
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

#3
record_defaults = [[0.],[0.],[0.],[0.]] #float이라 0.으로 넣음
xy = tf.decode_csv(value, record_defaults=record_defaults)

#이것들 역시 텐서
train_x_batch, train_y_batch = \ 
    tf.train.batch([xy[0:-1],xy[-1:]], batch_size=10) # x, y, 한번에 10개씩

sess ...

coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step ..

coord.request_stop()
coord.join(threads)

'''

"\n#1\nfilename_queue = tf.train.string_input_producer(['file1','file2',...],shuffle=False, name='filename_queue')\n\n#2\nreader = tf.TextLineReader()\nkey, value = reader.read(filename_queue)\n\n#3\nrecord_defaults = [[0.],[0.],[0.],[0.]] #float이라 0.으로 넣음\nxy = tf.decode_csv(value, record_defaults=record_defaults)\n\ntrain_x_batch, train_y_batch =     tf.train.batch([xy[0:-1],xy[-1:]], batch_size=10) # x, y, 한번에 10개씩\n\nsess ...\n"