In [6]:
# 변수를 여러개 주는 선형회귀

import tensorflow as tf

x1_data = [73.,93.,89.,96.,73.]
x2_data = [80.,88.,91.,98.,66.]
x3_data = [75.,93.,90.,100.,70.]
y_data = [152.,185.,180.,196.,142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]),name='weight1')
w2 = tf.Variable(tf.random_normal([1]),name='weight2')
w3 = tf.Variable(tf.random_normal([1]),name='weight3')
b = tf.Variable(tf.random_normal([1]),name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5) # 0.00001
train = optimizer.minimize(cost)

sess = tf.compat.v1.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost,hypothesis,train], feed_dict={x1:x1_data, x2:x2_data, x3:x3_data, Y:y_data})
    if step % 10 == 0 :
        print(step, "Cost:", cost_val, "\nPrediction:\n",hy_val)


0 Cost: 41093.355 
Prediction:
 [-27.507921 -32.454273 -32.609844 -32.54127  -26.888327]
10 Cost: 6.271926 
Prediction:
 [151.7982  183.06969 179.74376 198.70625 137.50519]
20 Cost: 5.8798914 
Prediction:
 [152.33475 183.72592 180.38452 199.40382 138.00873]
30 Cost: 5.86402 
Prediction:
 [152.33043 183.73207 180.38474 199.40387 138.01642]
40 Cost: 5.8482504 
Prediction:
 [152.32451 183.73625 180.38306 199.40181 138.02258]
50 Cost: 5.832551 
Prediction:
 [152.31859 183.74037 180.38133 199.39972 138.02872]
60 Cost: 5.816931 
Prediction:
 [152.31268 183.7445  180.37964 199.39766 138.03485]
70 Cost: 5.801379 
Prediction:
 [152.30681 183.74864 180.37796 199.3956  138.04097]
80 Cost: 5.785928 
Prediction:
 [152.30093 183.75275 180.37627 199.39354 138.04706]
90 Cost: 5.7705474 
Prediction:
 [152.29507 183.75684 180.37457 199.39148 138.05313]
100 Cost: 5.755233 
Prediction:
 [152.28926 183.76093 180.37291 199.38945 138.05922]
110 Cost: 5.7400174 
Prediction:
 [152.28342 183.76498 180.37122 199

1130 Cost: 4.5175176 
Prediction:
 [151.77017 184.12538 180.22481 199.19724 138.60928]
1140 Cost: 4.5082536 
Prediction:
 [151.76585 184.12842 180.22359 199.19556 138.61397]
1150 Cost: 4.4990153 
Prediction:
 [151.76155 184.13144 180.22237 199.19386 138.61864]
1160 Cost: 4.4897957 
Prediction:
 [151.75726 184.13448 180.22118 199.19217 138.6233 ]
1170 Cost: 4.48066 
Prediction:
 [151.75298 184.1375  180.21996 199.19049 138.62794]
1180 Cost: 4.4715505 
Prediction:
 [151.74872 184.1405  180.21875 199.1888  138.63257]
1190 Cost: 4.4624877 
Prediction:
 [151.74446 184.1435  180.21756 199.18712 138.63719]
1200 Cost: 4.4534187 
Prediction:
 [151.74022 184.1465  180.21635 199.18542 138.64182]
1210 Cost: 4.4444547 
Prediction:
 [151.73601 184.14949 180.21518 199.18378 138.64642]
1220 Cost: 4.435525 
Prediction:
 [151.73177 184.15245 180.21397 199.18208 138.65099]
1230 Cost: 4.426613 
Prediction:
 [151.72755 184.15541 180.21278 199.1804  138.65556]
1240 Cost: 4.4177446 
Prediction:
 [151.72336 1